name: Hopeful

on:
  push:
    branches:
      - main
      - master
      
env:
  MY_SECRET: ${{ secrets.HOPE }}

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Print Secret
        run: echo $MY_SECRET
